@startuml


Interface Runnable 
{
  +  run() : void
}


class CDownloader
{
   -  file : QFile 
   -  image : CImage 
   -  downloadFolder : QString 
   -  int size;
   -  int statusIndicator;
   -  bool isFinished;
   +  run() : void
}


class CError
{
  + someField
  # someMthod()
}

class CQuery
{
   + query : QString
   + someParamForQuery 
}


class CQueryEngine
{
    sendRequestToSearch() : void
    parseData() : void
}

class CImage
{
  - imageLink :   QUrl
  - imageName:    QString
  - imageInBytes: QByteArray
  
}

class CDownloaderEngine
{
   - poolDownloading : QThreadPool
}

class CImageDriver
{
  + isMarked: bool
  # markImage(): void
  # removeMarkedImage() : void
  # isImageMarked() : bool
  # mouseDoubleClick(QMouseEvent* event) : void
  # showImageByUrl  (QNetworkReply* reply): void 
}

note top of CFolderSetting : Class for set folder \nfor saving the pictures

class CFolderSetting
{
  # changeFolder : void ()
  # setDefaultFolder : void()
}

class CHistory
{
    + addHistory()
    # viewAllHistory()
}

class MainWindow
{
    + someField
    # someMthod()
}

CImageDriver o-- CImage
CImage *-- CDownloader
Runnable <|-- CDownloader
CQuery   <|-- CQueryEngine
CQueryEngine <|-- MainWindow
CHistory <|-- MainWindow
CFolderSetting <|-- MainWindow
CDownloader <|-- CDownloaderEngine
CDownloaderEngine <|-- MainWindow
CError <|-- CQueryEngine
@enduml
